### ISSUE TITLE
Please don't include that's already been included.

### ISSUE THREAD

**Issue by purnendudash** [Laboratoire-de-Chemoinformatique/moodle-qtype_reacsimilarity#3]
https://github.com/Laboratoire-de-Chemoinformatique/moodle-qtype_reacsimilarity/blob/b1ae08185666b71c89c14e01a40f2551918c95e8/edit_reacsimilarity_form.php#L51

**Comment by cperves** [comment]
I'll fix that fact as soon as possible
Originally put because the dev was not sure that chemdoodle libs works with modern jquery

**Comment by cperves** [comment]
@LouisPlyer I tested chemDoodle with jquery included by Moodle during the tiny_molstructure dev and it seems to work perfectly
