### ISSUE TITLE
Could you please share why this file and configuration is there.

### ISSUE THREAD

**Issue by purnendudash** [Laboratoire-de-Chemoinformatique/moodle-qtype_reacsimilarity#4]
https://github.com/Laboratoire-de-Chemoinformatique/moodle-qtype_reacsimilarity/blob/b1ae08185666b71c89c14e01a40f2551918c95e8/config-test.php#L27C13-L27C21

**Comment by cperves** [comment]
this configuration file is a kind of hook enabling us to launch unittest with a local isida server (also in our CI)
you can see this into the question_test.php file.
It enables to check that the plugin works well with its required evaluation server (provided in Api_server sub directory)
