### ISSUE TITLE
Could you please explain the utility of this function here.

### ISSUE THREAD

**Issue by purnendudash** [Laboratoire-de-Chemoinformatique/moodle-qtype_reacsimilarity#5]
https://github.com/Laboratoire-de-Chemoinformatique/moodle-qtype_reacsimilarity/blob/b1ae08185666b71c89c14e01a40f2551918c95e8/db/upgrade.php#L36

**Comment by cperves** [comment]
this function is usefull when you have  a previous version of the plugin enabling database upgrade
it won't be executed if your plugin is in the last version and only one time if you were in a previous version

**Comment by cperves** [comment]
This plugin was improved during this year, and is in our production server that's the reason why we let the upgrade file in is original state with the database modification

**Comment by purnendudash** [comment]
Kindly submit a clean code for us to review.

**Comment by cperves** [comment]
I can't remove the upgrade functions since some people in universities or other entities already use our plugin and need to upgrade the plugin

**Comment by cperves** [comment]
data tables associated with this plugin change over time while we improve the plugin
